<testsuite errors="1" failures="0" name="unittest.suite.TestSuite" tests="1" time="0.001">
  <testcase classname="__main__.qa_qpsk_demod_py_cb" name="test_001_t" time="0.0007">
    <error type="exceptions.NameError">global name 'multiply_py_ff' is not defined
  File "/usr/lib/python2.7/unittest/case.py", line 331, in run
    testMethod()
  File "qa_qpsk_demod_py_cb.py", line 38, in test_001_t
    mult = multiply_py_ff (2)
    </error>
  </testcase>
  <system-out><![CDATA[]]></system-out>
  <system-err><![CDATA[]]></system-err>
</testsuite>
